name: Marketbot CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # - name: Audit
      #   run: npm audit

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          directory: coverage

      - name: Build
        run: npm run build

      - name: Deploy
        if: github.event_name == 'push'
        run: npx -q @ionaru/teamcity-deploy teamcity.saturnserver.org MarketBot_Build_3 ${{ secrets.API_TOKEN }}
