name: Marketbot CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          # TODO: Lock version when https://github.com/oven-sh/setup-bun/issues/37 is fixed.
          bun-version: latest

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun run test

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          directory: coverage

      - name: Deploy
        if: github.event_name == 'push'
        run: bunx @ionaru/teamcity-deploy teamcity.saturnserver.org MarketBot_Build ${{ secrets.API_TOKEN }}
